import { Footer } from "app/Components/shared/Footer";
import { Header } from "app/Components/shared/Header/Header";
import "app/sass/globals.sass";
import type { Metadata } from "next";
// import { Inter } from "next/font/google";
import { Raleway } from "next/font/google";

// const inter = Inter({ subsets: ["latin"] });

const raleway = Raleway({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Lolo Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      {/* <body className={inter.className}> */}
      <body className={raleway.className}>
        <Header />
        {/* <Hero />
        <Description /> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
